create table user(
	seq int primary key generated by default as identity(start with 1, increment by 1),
	user_id varchar(20) not null,
	password varchar(20) not null,
	user_name varchar(20) not null
);